auth:
  password: redis
master:
  persistence:
    size: 8Gi
  resources:
    requests:
      memory: 8Gi
      cpu: 1
replica:
  replicaCount: 1
  persistence:
    size: 4Gi
  resources:
    requests:
      memory: 4Gi
      cpu: 1